# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Obj-C-FusionTables' do
    pod 'Obj-C-FusionTables'
end

target 'Obj-C-FusionTablesTests' do
    pod 'Obj-C-FusionTables'
end

